### ISSUE TITLE
Audio from 3.5mm does not work

### ISSUE THREAD

**Issue by superzeldalink** [aytic/Lenovo-Flex-15-Hackintosh#1]
Audio output from 3.5mm does not work. But Audio settings still detected as Headphone. 
Fix please...

**Comment by aytic** [comment]
It is working fine for me. Show me your audio settings please.
![screen shot 2018-06-20 at 18 26 43](https://user-images.githubusercontent.com/8146736/41671480-860355ce-74b7-11e8-802d-12267cff5ee3.png)

**Comment by superzeldalink** [comment]
It’s OK now, I just reinstall the kext with kext wizard and it’s working now
Thanks :)
